### ISSUE TITLE
[Tracking] Add more common field types.

### ISSUE THREAD

**Issue by TkTech** [TkTech/sachi#3]
We should have a good set of pre-implemented fields.

- [x] `TextField` - stemmed/tokenized strings
- [x] `StringField` - literal strings
- [ ] `DateTimeField` - Simple Python `datetime` container.
- [ ] `BooleanField` - Simple Python `boolean` container.
